Chapter5
OleJune/think_python pull request #2
Opened 2022-11-14 15:20 UTC by OleJune

2022-12-13 14:51 UTC, auraz requested changes
Overall looks very good! Please address minor comments.

2022-12-13 14:51 UTC, auraz commented on chapter5/5-1.py
> +local_time = time.strftime('%H:%M:%S')
The idea of task is to get local time from the seconds (similar like you did with days). Please update the code. (w/o calling strftime)

2022-12-13 14:51 UTC, auraz commented on chapter5/5-4.py
> +def recurse(n, s):
please send stack diagram photo, as per task requirements.

2022-12-13 14:51 UTC, auraz commented on chapter5/5-4.py
> +	Prints the value of 's' when 'n == 0'.
Please update docstring with explaining the idea of this function. E.g. Right now docstring is explaining only lines 9 and 10.

2022-12-13 14:51 UTC, auraz commented on chapter5/5-2_prompt.py
> +def check_fermat(a, b, c, n):
Good!

2022-12-13 14:51 UTC, auraz commented on chapter5/5-3.py
> +def is_triangle(a, b, c):
Good!

2022-12-13 14:51 UTC, auraz commented on chapter5/5-4.py
> +#recurse(-1, 0)  #this is an infinite recursion that causes a runtime error
Good!

2022-12-13 14:51 UTC, auraz commented on chapter5/5-6.py
> +import turtle as t
Good!

2022-12-15 12:27 UTC, OleJune commented on chapter5/5-1.py
> +local_time = time.strftime('%H:%M:%S')
Fixed

2022-12-15 12:27 UTC, OleJune commented on chapter5/5-4.py
> +	Prints the value of 's' when 'n == 0'.
Fixed

2022-12-15 12:28 UTC, OleJune commented on chapter5/5-4.py
> +def recurse(n, s):
Sent

2022-12-15 12:52 UTC, auraz requested changes
Another pass, very good, please continue.

2022-12-15 12:52 UTC, auraz commented on chapter5/5-4.py
> +	# or: The function calls itself until argument1 (n) equals 0
This line is good

2022-12-15 12:52 UTC, auraz commented on chapter5/5-4.py
> +	#		and then returns the value of argument2 (s).
This line needs extension, in the end of the line please add, and in this case, value of s will be equal to?

2022-12-15 16:20 UTC, auraz approved these changes
Good job!
You can merge!

2022-12-15 19:24 UTC, merged